services:
  - type: web
    name: pulmoscan-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PERSIST_DIR
        value: /var/data
      - key: SECRET_KEY
        generateValue: true
